{% set name = "numpydoc_decorator" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/numpydoc_decorator-{{ version }}.tar.gz
  sha256: 926ac094d4423561a06d4c851f555bfafd0fd723a6f2d47b8449ae9d2f579c32

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.11
    - poetry-core
    - pip
  run:
    - python >=3.7.1,<3.11
    - typing_extensions

test:
  imports:
    - numpydoc_decorator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alimanfoo/numpydoc_decorator
  summary: Build numpy-style docstrings programmatically and apply them using a decorator
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
