{% set name = "numpydoc_decorator" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/numpydoc_decorator-{{ version }}.tar.gz
  sha256: 8e09e63613fbec2bac96a93ac5e6cd322856c97dc8b91cb63d80bdcabdb9c8b8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - poetry-core
    - pip
  run:
    - python >=3.9,<3.13
    - typing_extensions

test:
  imports:
    - numpydoc_decorator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alimanfoo/numpydoc_decorator
  summary: Build numpy-style docstrings programmatically and apply them using a decorator
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
