{% set name = "numpydoc_decorator" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/numpydoc_decorator-{{ version }}.tar.gz
  sha256: 880e4dcf634aa36fd4815051e21f79c8a370c3bcd5ba1fa5fb9a6e27222d4b8c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - poetry-core
    - pip
  run:
    - python >=3.8.1,<3.12
    - typing_extensions *

test:
  imports:
    - numpydoc_decorator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alimanfoo/numpydoc_decorator
  summary: Build numpy-style docstrings programmatically and apply them using a decorator
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
